           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENCE
                   Version 4.0, July 2019

           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENCE
  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION, AND MODIFICATION

 0. You just DO WHAT THE FUCK YOU WANT TO.
